openapi: 3.1.0
info:
  title: Quizable API (Auth + Theme Foundation)
  version: 0.1.0
  description: Minimal contracts for auth check; rooms/groups deferred to future features
servers:
  - url: https://localhost:3000
paths:
  /api/auth/me:
    get:
      summary: Get current user info
      security:
        - clerkAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized

components:
  securitySchemes:
    clerkAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        userId: { type: string }
        displayName: { type: string }
        imageUrl: { type: string }
