name = "trivia-room-workers"
main = "room-durable-object.ts"
compatibility_date = "2025-10-30"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "RoomDurableObject"
script_name = "trivia-room-workers"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDurableObject"]